USE [master]
GO

/****** Object:  Database [OurFirstDatabase]    Script Date: 2022/08/15 20:45:03 ******/
CREATE DATABASE [OurFirstDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OurFirstDatabase', FILENAME = N'C:\SQL_Data_Files\OurFirstDatabase.mdf' , SIZE = 65536KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OurFirstDatabase_log', FILENAME = N'C:\SQL_Log_Files\OurFirstDatabase_log.ldf' , SIZE = 32768KB , MAXSIZE = 524288KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OurFirstDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OurFirstDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OurFirstDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OurFirstDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OurFirstDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OurFirstDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OurFirstDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [OurFirstDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OurFirstDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OurFirstDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OurFirstDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OurFirstDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OurFirstDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OurFirstDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OurFirstDatabase] SET  READ_WRITE 
GO


